# Generated by Django 5.0.6 on 2026-03-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_no",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "balance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("opened_at", models.DateTimeField()),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("ledger_json", models.JSONField(default=dict)),
                ("ext_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_no",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "mobile",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "amount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("profile_json", models.JSONField(default=dict)),
                ("tags_json", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Cdr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cdr_no", models.CharField(db_index=True, max_length=40, unique=True)),
                ("charge_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("cdr_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("route_json", models.JSONField(default=dict)),
                ("extra_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cdrs",
                        to="banktel.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cdrs",
                        to="banktel.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-cdr_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BillMonthly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_month", models.CharField(db_index=True, max_length=7)),
                ("bill_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("generated_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("summary_json", models.JSONField(default=dict)),
                ("detail_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="banktel.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="banktel.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="account",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="banktel.customer",
            ),
        ),
        migrations.CreateModel(
            name="RiskCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_no",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("risk_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("detected_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("rules_json", models.JSONField(default=dict)),
                ("evidence_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_cases",
                        to="banktel.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_cases",
                        to="banktel.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Txn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txn_no", models.CharField(db_index=True, max_length=40, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("txn_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("payload_json", models.JSONField(default=dict)),
                ("tags_json", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="txns",
                        to="banktel.account",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="txns",
                        to="banktel.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-txn_at", "-id"],
            },
        ),
    ]
