# Generated by Django 3.2.25 on 2026-03-05 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banktel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcase',
            name='linked_txn_no',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='riskcase',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='riskcase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_review_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskcase',
            name='risk_phase',
            field=models.CharField(choices=[('OPEN', '已打开'), ('REVIEWING', '审核中'), ('BLOCKED', '已拦截'), ('RELEASED', '已放行'), ('CLOSED', '已闭环')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='txn',
            name='checker_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txn_checker_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='txn',
            name='core_phase',
            field=models.CharField(choices=[('RECEIVED', '受理'), ('REVIEW_PENDING', '待复核'), ('APPROVED', '复核通过'), ('REJECTED', '复核拒绝'), ('BOOKED', '记账完成'), ('CLEARED', '清算完成'), ('ACKED', '回执完成')], db_index=True, default='RECEIVED', max_length=20),
        ),
        migrations.AddField(
            model_name='txn',
            name='maker_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txn_maker_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='txn',
            name='phase_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
